### ISSUE TITLE
Trust Relationship issue

### ISSUE THREAD

**Issue by cuotos** [GorillaStack/auto-tag#1]
I'm pretty new to Lambda and had to make a change to get auto-tag working and just wanted to make sure it wasn't something I missed.

The role that has permission to tag items, I had to update its Trust Relationship, specifying the Lambda role to be trusted. by default it was "service: lambda.amazonaws.com".

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::[account running lambda]:role/AutoTagLambdaRole"
      },
      "Action": "sts:AssumeRole"
    }
  ]

Without doing this, I get the following:

`User: arn:aws:sts::[my account]:assumed-role/AutoTagLambdaRole/awslambda_20160209121944195 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[my account]:role/AutoTagRole`

It is the AutoTagLambdaRole that appears to need to be trusted, not lambda.amazonaws.com.

If this is correct, ill happily update the doco.

**Comment by peterpakos** [comment]
Thanks for the heads-up @cuotos.

I'm having issues with getting this to work.

Did you have to set up event source within your lambda autotag function?

**Comment by cuotos** [comment]
Yes, once cloudtrail is logging to an s3 bucket, you can create an even to be triggered when something is created in the bucket.
event source: S3
Bucket: Your bucket that has your cloudtrail logs
Event Type: Object Created

**Comment by peterpakos** [comment]
Thanks @cuotos, this is exactly how I had it set up. For some reason it was very unreliable and kept tagging only around 10% of all resources (instances).

I ended up with writing my own lambda function in Python.

**Comment by bstaszcuk** [comment]
@peterpakos would you be willing to share your Python function?

**Comment by peterpakos** [comment]
@bstaszcuk sure, have a look [here](https://github.com/peterpakos/cloud_tools/blob/master/lambda_function)

I'll update [README file](https://github.com/peterpakos/cloud_tools/blob/master/README.md) with install instructions too.

**Comment by em0ney** [comment]
Hi @cuotos,

Sorry for the lag on this. Yes, it is the AutoTagLambdaRole that needs to be trusted by the AutoTagRole, such that is can be assumed for tagging.

Feel free to create a PR to improve the documentation
