### ISSUE TITLE
retro-tag repo - is it being monitored for issues?

### ISSUE THREAD

**Issue by ecout** [GorillaStack/auto-tag#100]
Hello team,

Is anyone still monitoring the retro-tag repository?
Considering the main difference is the way events are processed, because the Lambda source code is exactly the same(only the handler being used differs) and that the issue I filed there is related to the Ruby script and neither the Cloud Formation or the Lambda function I'm wondering if it'll get addressed:
https://github.com/GorillaStack/retro-tag/issues/12

Thank You!

**Comment by rayjanoka** [comment]
yes :D
