### ISSUE TITLE
Lambda Access Denied Error

### ISSUE THREAD

**Issue by harsh541** [GorillaStack/auto-tag#105]
The follow error is shown when running the autotag_event_main-template.json:

ResourceLogicalId:AutoTagLambdaFunction, ResourceType:AWS::Lambda::Function, ResourceStatusReason:Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for gorillastack-autotag-releases-us-west-2/autotag-0.5.3.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 428ddb8d-230d-4c2b-933b-4d801f44f144, Extended Request ID: null)" (RequestToken: 9aa9b0ac-0499-730d-b6d7-dca41244407d, HandlerErrorCode: AccessDenied).

**Comment by rayjanoka** [comment]
We aren't hosting the zip files any longer, you can grab it from the release page and host it in your own bucket or use the deploy script.
