### ISSUE TITLE
Lambda runtime error

### ISSUE THREAD

**Issue by estanqueiroa** [GorillaStack/auto-tag#114]
"errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/workers/autotag_default_worker.js\n- /var/task/autotag_factory.js\n- /var/task/aws_cloud_trail_event_listener.js\n- /var/task/autotag_event.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'"
[

notes: If your lambda runtime is nodejs18.x my understanding is that SDK v2 is not included in the runtime. So, the best solution would be to switch to v3 SDK

**Comment by tkboyle** [comment]
I'm also seeing this when switching the runtime from nodejs:14 to nodejs:18.

No issues using nodejs:16.v18

**Comment by vishaliamops** [comment]
Facing the issue @northern @humblelistener 

Getting error:
`errorType": "Runtime.UnhandledPromiseRejection,
 errorMessage": "Error: Cannot find module 'aws-sdk'\nRequire stack:`

**Comment by rayjanoka** [comment]
I've updated the v0.5.5 release package to include the `aws-sdk` v2 library for NodeJS 18 in Lambda.

**Comment by estanqueiroa** [comment]
hello there, just tested and got this error msg:

2023-09-06T18:20:21.370Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Cannot use import statement outside a module",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Cannot use import statement outside a module",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1058:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
}


thank you

**Comment by rayjanoka** [comment]
thanks @estanqueiroa, I think I got the errors cleared if you could try again.

**Comment by vishaliamops** [comment]
Hello @rayjanoka I think the issue is not resolved yet, Facing same error again.

**Comment by rayjanoka** [comment]
@vishaliamops ok I uploaded the code, you can try `update-master` again.

**Comment by vishaliamops** [comment]
Thank you will check and let you know the status.

**Comment by vishaliamops** [comment]
Good Morning @rayjanoka 
I think the SDK issue is resolved but now we are getting new error,

{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "SyntaxError: Cannot use import statement outside a module",
    "reason": {
        "errorType": "SyntaxError",
        "errorMessage": "Cannot use import statement outside a module",
        "stack": [
            "/var/task/autotag_event.js:1",
            "import AwsCloudTrailEventListener from './aws_cloud_trail_event_listener.js';",
            "^^^^^^",
            "",
            "SyntaxError: Cannot use import statement outside a module",
            "    at internalCompileFunction (node:internal/vm:73:18)",
            "    at wrapSafe (node:internal/modules/cjs/loader:1178:20)",
            "    at Module._compile (node:internal/modules/cjs/loader:1220:27)",
            "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
            "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
            "    at Module._load (node:internal/modules/cjs/loader:960:12)",
            "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
            "    at require (node:internal/modules/cjs/helpers:121:18)",
            "    at _tryImportOrRequire (/opt/nodejs/node_modules/lumigo-auto-instrument/aws/aws-user-function.js:211:14)",
            "    at _loadUserAppAsync (/opt/nodejs/node_modules/lumigo-auto-instrument/aws/aws-user-function.js:133:12)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: SyntaxError: Cannot use import statement outside a module",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)",
        "    at process.emit (node:events:514:28)",
        "    at emit (node:internal/process/promises:149:20)",
        "    at processPromiseRejections (node:internal/process/promises:283:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}

**Comment by rayjanoka** [comment]
ok, I fully tested this one in my account. Should be good to go with `aws-sdk v3`!

https://github.com/GorillaStack/auto-tag/releases/tag/0.5.7

**Comment by vishaliamops** [comment]
Thank you @rayjanoka The issue is resolved and the auto tag is working fine with Node 18.x version.

**Comment by estanqueiroa** [comment]
Thanks a lot for your help! Outstanding work
