### ISSUE TITLE
no assets available for 0.5.10

### ISSUE THREAD

**Issue by robertwilkinson9** [GorillaStack/auto-tag#123]
assets missing for 0.5.10

the default for deploy_autotag.sh is 0.5.10 - but it fails - there are no assets listed in the JSON file.

debug ....

RELEASE_URL_QUERY is       .[] | select(.name = "0.5.10") |
      .assets[] | select( .name == "autotag-0.5.10.zip") |
      .browser_download_url
GITHUB_API_RELEASES_URL is https://api.github.com/repos/GorillaStack/auto-tag/releases
RELEASE_ZIP_FILE_URL is 
curl: (3) URL using bad/illegal format or missing URL

works with 0.5.9

**Comment by rayjanoka** [comment]
ok, I think I have it up there now. Let me know.

**Comment by robertwilkinson9** [comment]
worked fine. thanks
