### ISSUE TITLE
Error while deploying to AWS

### ISSUE THREAD

**Issue by vidalfontoura** [GorillaStack/auto-tag#13]
Hello guys I'm trying to follow the installation steps in the README.md.
And I'm receiving this error from the Lambda output.

Can someone help me with that one?

![image](https://cloud.githubusercontent.com/assets/11443512/22713229/babdd68a-ed6e-11e6-9b18-a010b3234858.png)

**Comment by joelplums** [comment]
Just opened a PR with a fix. The fix handles cases where unzipped CloudTrail logs are empty. Link here https://github.com/GorillaStack/auto-tag/pull/14/commits/4cc63f52a4723d43fc24d26bcd9e02b4a56b4107

**Comment by vidalfontoura** [comment]
@joelplums  Thanks I will checkout and try it

**Comment by em0ney** [comment]
Marking resolved,  @vidalfontoura please reachout if you still have issues

**Comment by vidalfontoura** [comment]
@em0ney. Yeah that issue was resolved I missed marking as resolved. thanks
