### ISSUE TITLE
"errorMessage": "Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by shanitgupta** [GorillaStack/auto-tag#16]
I installed AutoTag on Friday and it seemed to be working fine (I verified it was working). Starting Sunday I started seeing errors and nothing was getting tagged. Here is the error I am seeing 

{
  "errorMessage": "Cannot read property '0' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "/var/task/aws_cloud_trail_listener.js:98:58",
    "new Promise (/var/task/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)",
    "AwsCloudTrailListener.retrieveLogFileDetails (/var/task/aws_cloud_trail_listener.js:96:14)",
    "_callee$ (/var/task/aws_cloud_trail_listener.js:62:30)",
    "tryCatch (/var/task/node_modules/babel-regenerator-runtime/runtime.js:61:40)",
    "GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/babel-regenerator-runtime/runtime.js:329:22)",
    "GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/babel-regenerator-runtime/runtime.js:94:21)",
    "onFulfilled (/var/task/node_modules/co/index.js:65:19)",
    "/var/task/node_modules/co/index.js:54:5",
    "new Promise (/var/task/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)"
  ]
}

The CloudTrail logs seem fine. I was able to download them and see valid content. If there are instructions to self host the code with modifications that will help a lot.

**Comment by jkovolski** [comment]
Any luck with this?  I'm seeing the same issue.

**Comment by shanitgupta** [comment]
I made some changes to the code and now it is working well. I can send them to you if you are interested. 
-Shanit 

    On Friday, March 31, 2017 11:01 AM, jkovolski <notifications@github.com> wrote:
 

 Any luck with this? I'm seeing the same issue.—

**Comment by jkovolski** [comment]
Sure, that would be appreciated.  Thank you.

**Comment by shanitgupta** [comment]
You can get it from Autotag
  
|  
|    |  
Autotag
 Autotag  |  |

  |

 

I haven't cleaned up the readme and such. 
Look at the instructions at shanit.notes.rtf
Definitely update values in- infra_parameters.sh- src/workers/autotag_default_worker.js:var AUTOTAG_TAG_NAME = 'carbon_creator';
If you run into issues I am happy to help. I found this very useful. 
-Shanit  

    On Friday, March 31, 2017 12:18 PM, jkovolski <notifications@github.com> wrote:
 

 Sure, that would be appreciated. Thank you.—

**Comment by em0ney** [comment]
Hi @shanitgupta,

Can you please submit a pull request for your changes?  If there is a bug, it would be great to have it resolved here for all users!

Thanks,
Elliott

**Comment by em0ney** [comment]
Hi @shanitgupta,

Can you share a PR?
