### ISSUE TITLE
Unable to Edit React Libraries Within Lambda

### ISSUE THREAD

**Issue by patalwell** [GorillaStack/auto-tag#20]
Hi Guys,

Thanks so much for this solution! When I attempt to edit some of the react classes and components within your zip file and upload the refactored code to Lambda, I receive the following error. Not sure what's going on as the file still contains all of the same modules before the changes I've made.

I have specifically changed static variables and functions in the autotag_default_worker.js file. I am attempting to retrieve the User Name vice the ARN from AWS.

```
var AUTOTAG_TAG_NAME = 'User';
var ROLE_PREFIX = 'arn:aws:iam::';
var ROLE_SUFFIX = ':role';
var DEFAULT_STACK_NAME = 'autotag';
var MASTER_ROLE_NAME = 'AutoTagMasterRole';
var MASTER_ROLE_PATH = '/gorillastack/autotag/master/';
```

```
    key: 'getAutotagPair',
    value: function getAutotagPair() {
      return {
        Key: this.getTagName(),
        Value: this.getTagValue()
      };
    }
  }, {
    key: 'getTagName',
    value: function getTagName() {
      return AUTOTAG_TAG_NAME;
    }
  }, {
    key: 'getTagValue',
    value: function getTagValue() {
      return this.event.userIdentity.userName;
    }
  }]);

  return AutotagDefaultWorker;
}();
```

 Here is the error message I recieve in Lambda.

```
{
  "errorMessage": "Cannot find module '/var/task/autotag'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}
```

Please let me know your thoughts.

Kind Regards

-Pat

**Comment by em0ney** [comment]
Hi Pat,

I think I'll need a bit more code to understand what's going on.  Have you forked our repository?  If so, send me a URL to the files in question on your fork.

To me it appears that somewhere you are trying to load a javascript module named '/var/task/autotag'.

I'll be able to tell more if I can see your code to eyeball the error or further check it out and try reproduce your issue

**Comment by patalwell** [comment]
Hey Elliot,

Thats the thing, I am downloading the zipped React files from your site and tried to upload the code directly to Lambda, without altering anything. I’ll look at the repo and compare it to the version I have stashed on my desktop to see if the module is indeed missing. 

Albeit, Lambda can sometimes be “buggy”. I’ll let you know more details.

-Pat


Pat Alwell
Big Data Engineer & Business Development Manager
Algebraix Data
http://www.patalwell.com
San Diego, CA

Cell: 540-226-7365
Email: pat.alwell@gmail.com
———————————————
Sales, Strategy, & Marketing
Check out my Linked In Profile:www.linkedin.com/in/patalwell
Follow me on Twitter Here:www.twitter.com/PatAlwell

**Comment by em0ney** [comment]
Hi there @patalwell,

Going to close this until I hear back with more details.

Thanks,
Elliott
