### ISSUE TITLE
How could you install autotag for multiple regions? I did do this and it did not work:

### ISSUE THREAD

**Issue by faribakes** [GorillaStack/auto-tag#21]
How do you tag multi regions. updating CodeS3Bucket with  "gorillastack-autotag-releases-ap-northeast-1, gorillastack-autotag-releases-us-west-2" did not work.

**Comment by nskitch** [comment]
The buckets you mentioned above are public, it's the cloudformation template that needs to be run in each region that sets up the roles, cloudtrail, lamdba that reaches out to the s3 buckets you mentioned above.

**Comment by em0ney** [comment]
We simply have a version of the code in each region to make it easy to deploy in any region.

You can set up cloudtrail to operate over all regions, which means you will only need to deploy auto-tag in a single region.

Furthermore, you can write CloudTrail logs from multiple accounts into an s3 bucket in your master account and use roles for cross account access to set up cross account auto-tagging.  This is outlined and illustrated with a diagram in this blog post https://blog.gorillastack.com/gorillastack-presents-auto-tag

I'll mark this as closed.  If you have further questions regarding getting setup, feel free to DM me in our public slack.  Get your invite at https://chat.gorillastack.com
