### ISSUE TITLE
S3-hosted code is massively different from github-hosted code

### ISSUE THREAD

**Issue by seren** [GorillaStack/auto-tag#24]
The `autotag-0.3.0.zip` version of the code that the cloudformation template installs from S3 seems to have had a major refactor from the tagged 0.3.0 version in github.

This is not only strange but a bit concerning since anyone checking out this repo and following the setup instructions is running code that is quite different from what they would assume.

**Comment by em0ney** [comment]
Hi @seren,

Sorry, bit behind on doing some maintenance on this repository.

I will be building a fresh version of the hosted code, as well as setting up some automation to deploy these zip files automatically on successful master builds (so this shouldn't ever happen again).

Does that sound like a reasonable approach?

Thanks for bringing this to my attention,
Elliott

**Comment by seren** [comment]
That sounds great. Thanks!

**Comment by rayj-pgi** [comment]
I believe they look different because the code in the repo is ES6 and the zip converted to ES5 for Lambda.
