### ISSUE TITLE
cross account access not working

### ISSUE THREAD

**Issue by Dhruvin1** [GorillaStack/auto-tag#28]
I have been using Autotag for almost a month now, and it is functioning satisfactorily in all the regions. Now, I need to cover all my accounts. Can you explain how to move with that?
Just for your review, I created a role in my other account and trusted my account where autotag is working, I also added an inline policy in my Autotag execution role to assume the role in the other account. However, it is still not working. What else is needed?

**Comment by Dhruvin1** [comment]
Alright, so I figured it out by myself. Now it is working cross account.

**Comment by srviljoen** [comment]
@Dhruvin1 Hi, struggling with this exact issue at the moment. Have autotag installed (using the CF template) in an organization Master account and trying to get it working now in the member account. Could you provide details how you got it working in the 2nd account pls.
Thanks.
