### ISSUE TITLE
exception "errorMessage": "Cannot read property '0' of undefined" 

### ISSUE THREAD

**Issue by nalinbAWS** [GorillaStack/auto-tag#34]
{
  "errorMessage": "Cannot read property '0' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "/var/task/aws_cloud_trail_listener.js:98:58",
    "new Promise (/var/task/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)",
    "AwsCloudTrailListener.retrieveLogFileDetails (/var/task/aws_cloud_trail_listener.js:96:14)",
    "_callee$ (/var/task/aws_cloud_trail_listener.js:62:30)",
    "tryCatch (/var/task/node_modules/babel-regenerator-runtime/runtime.js:61:40)",
    "GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/babel-regenerator-runtime/runtime.js:329:22)",
    "GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/babel-regenerator-runtime/runtime.js:94:21)",
    "onFulfilled (/var/task/node_modules/co/index.js:65:19)",
    "/var/task/node_modules/co/index.js:54:5",
    "new Promise (/var/task/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)"
  ]
}

**Comment by rayj-pgi** [comment]
This was resolved by #31
