### ISSUE TITLE
Add additional tags

### ISSUE THREAD

**Issue by peaceofanotherkind** [GorillaStack/auto-tag#35]
I know this is pretty basic, but I'm new to this and having some trouble. I'd like to have additional tags added to each, in addition to the owner of the resource. Is there a way to add this to the script?

**Comment by Rizbe** [comment]
Bump

Would like to know the same

**Comment by rayj-pgi** [comment]
I don't think it makes sense to have AutoTag do this. AutoTag is tagging **all** snapshots so I'm not sure how AutoTag would know if this was one of your Backups or some other snapshot.

You can just tag the "Backup" snapshot with your tags when your function sends the snapshot create request.

See the "TagSpecification" Request Parameters of the CreateSnapshot API call.
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html

**Comment by peaceofanotherkind** [comment]
What I’m trying to do is make sure all EC2 instances are tagged with this so they will be backed-up automatically. Otherwise users may forget to add the tag when they create the VM. 

On Jun 9, 2018, at 3:37 PM, Ray <notifications@github.com> wrote:

I don't think it makes sense to have AutoTag do this. AutoTag is tagging all snapshots so I'm not sure how AutoTag would know if this was one of your Backups or some other snapshot.

You can just tag the "Backup" snapshot with your tags when your function sends the snapshot create request.

See the "TagSpecification" Request Parameters of the CreateSnapshot API call.
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSnapshot.html

**Comment by rayj-pgi** [comment]
Ok. 

One suggestion would be to create the opposite system and only tag the EC2 instances that you do NOT need the backup, that is if your backup function that creates the snapshots can query for all instances except those with the tag...

**Comment by rayj-pgi** [comment]
Another suggestion would be to strictly enforce the tag key and value for all EC2 RunInstances actions with IAM. This way will not allow the user to create the instance unless the tag is there. 

Here they have a good example of how to use the IAM Condition Key "aws:RequestTag/tag-key" for enforcing key/value under "Creating a Volume with Tags".
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ExamplePolicies_EC2.html

Your IAM policy might looks something like this...
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "EnforceOpsAutomatorTagOnInstances",
      "Effect": "Allow",
      "Action": "ec2:RunInstances",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "aws:RequestTag/OpsAutomator": "Backup"
         }
       }
     }
  ]
}
```

**Comment by peaceofanotherkind** [comment]
Ultimately I just want every EC2 instance to be tagged with, "OpsAutomator=Backup" so that the OpsAutomator stack will automatically back it up according to our backup/retention policy. If we have a request for a specific resource to NOT be backed-up, then we can remove the tag. Since this is what we're using to auto-tag resources, it just seemed more logical to have auto-tag do this, rather than re-configuring everything else.

**Comment by rayj-pgi** [comment]
If you are using the code from master, you could fork it and add the tag to the "createTags" call in "src/workers/autotag_ec2_worker.js". 
Then every instance will get the tag, but I don't think we would add this as a feature in general.

```
tagEC2Resources(resources) {
    let _this = this;
    return new Promise((resolve, reject) => {
      try {
        _this.ec2.createTags({
          Resources: resources,
          Tags: [
            _this.getAutotagPair(),
           {Key: 'OpsAutomater', Value: 'Backup'}
          ]
        }, (err, res) => {
          if (err) {
            reject(err);
          } else {
            resolve(true);
          }
        });
      } catch (e) {
        reject(e);
      }
    });
  }
```

**Comment by peaceofanotherkind** [comment]
This worked perfectly! Thank you so much!

**Comment by Nipazz** [comment]
Would adding additional tags be possible in the Default_Worker? So every new resource would get the additional tag, regardless of the resource type?

**Comment by rayj-pgi** [comment]
> Would adding additional tags be possible in the Default_Worker? So every new resource would get the additional tag, regardless of the resource type?

Hey Nipazz, 

I think you'd want to just add it here in the default_worker...

```js
getAutotagTags() {
    return [
      {someNewTagKey: 'someNewKeyValue'},
      this.getAutotagCreatorTag(),
      ...(SETTINGS.AutoTags.CreateTime ? [this.getAutotagCreateTimeTag()] : []),
      ...(this.getInvokedByTagValue() && SETTINGS.AutoTags.InvokedBy ? [this.getAutotagInvokedByTag()] : []),
    ];
  }
```
