### ISSUE TITLE
How to setup the IAM policy for autotag

### ISSUE THREAD

**Issue by wangliu-talendbj** [GorillaStack/auto-tag#36]
Hi
   I'm following the https://www.gorillastack.com/news/gorillastack-presents-auto-tag/. From the process it mentioned, I have to setup policy for lambda and autotag.
Could you make it more specific that code for the policy? I see several policies in the cloudformation template, and I've no idea which part I need.
Appreciate it for your answer

**Comment by em0ney** [comment]
Hi,

Can I get an idea of how you are trying to use autotag?  Is it to use on a cross-account cloudtrail?

What specific part of the policy is causing you concern at the moment?

**Comment by wangliu-talendbj** [comment]
Hi 
  Thanks for your reply. Actually, you're right. I decide to use this on a cross-account cloudtrail.
I have a few questions here,
1) do I need to install the cloudformation template in each account including linked and master ?
2) I see in the description, it say `On each account, set-up the provided policy for Auto Tag to assume (to perform tagging)`, would you mind making it more specific what I should do in this step? Do you mean I have to create a role called `AutoTag`, and write the policy for it? If so, where's the code for the policy?
Appreciate it for your answer

**Comment by rayj-pgi** [comment]
This has been open for a while, check out the updated README and let us know if you are still having issues.
