### ISSUE TITLE
Can auto-tag function stop tagging after detecting the ec2 are already tagged with specific tags?

### ISSUE THREAD

**Issue by wangliu-talendbj** [GorillaStack/auto-tag#38]
Hi again
    Currently, we have a new feature requirement to implement. Here's the scenario, when we're going to launch a new ec2 instance and the new instance has already been tagged as certain key/value using userdata or whatever. By default, the new instance will be tagged by auto-tag function as well.
    Is that possible that the auto-tag function won't perform the tagging operation after detecting that the ec2 has already been tagged with specific tags ?
   Appreciate it for your answer, many thanks

**Comment by rayj-pgi** [comment]
This would require an additional API scan of the tags before applying any tags. I don't think we are interested in adding this feature at this time.
