### ISSUE TITLE
"Unable to import module 'autotag_event'"error.

### ISSUE THREAD

**Issue by NeuralMiner** [GorillaStack/auto-tag#42]
Hello,
I'm seeing the above error (from Lambda) when a new instance is created. The instance is not being tagged successfully.
I used the "CloudWatch Events Method - Multi-Region" method to install/deploy.

Full error:
```
Unable to import module 'autotag_event': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```
Thanks for taking a look.

**Comment by rayj-pgi** [comment]
Hey, What does your deployment zip look like? There should be a file called 'autotag_event.js'.

**Comment by NeuralMiner** [comment]
Heyo.

I don't see a `autotag_event.js` anywhere in the zip (did a `dir /s /b` and searched for the file name).
I manually pulled it from http://gorillastack-autotag-releases-us-east-1.s3.amazonaws.com/autotag-0.3.0.zip as well and don't see it in there.

Root folder:
> node_modules
> workers
> autotag.js
> autotag_factory.js
> aws_cloud_trail_listener.js
> cloud_trail_event_config.js

**Comment by rayj-pgi** [comment]
I see, you are using the old code with the new instructions. 

If you want to use the latest version, which has many updates, you'll need to build a zip yourself from the master branch using the instructions from the README under "Generate the Lambda zip package". 

Or you can use the 0.3.0 zip and go back to 5bd4c8c and use those instructions.

Or we can wait until Elliot pushes the new zip out to the gorillastack bucket.

**Comment by NeuralMiner** [comment]
Ahhhhh, ok. That makes sense. Thank you very much for the help. Really appreciate it.

**Comment by NeuralMiner** [comment]
I went ahead and did the build and updated the stack. Worked like a champ. Thanks again.
Closing.

**Comment by rayj-pgi** [comment]
Great news! thanks.

**Comment by hoanglc** [comment]
Thanks for this review. I'm able to use service auto-tag. it works like a charm after seeing this.

**Comment by zeiguy** [comment]
I think I am confused, I am new to this.
Where should I be generating the Lambda zip package? In an EC2 instance? I entered all those lines in the CLI of an EC2 instance and found the autotag_event.js file, but I am unsure what to do from here. Any help is appreciated
