### ISSUE TITLE
AutoTag_Creator - Can the value for this tag be just email of the creator?

### ISSUE THREAD

**Issue by mkadali99** [GorillaStack/auto-tag#48]
When a resource is tagged with key, the value is something like this, arn:aws:sts::Account-number:assumed-role/Account-name/xxxxxxxxxx@domain.com.
Can this be customized that, only the email id is tagged as the key?
Like 
AutoTag_Creator : xxxxxxxxxx@domain.com.

**Comment by rayj-pgi** [comment]
We could, but there are many different formats besides the sts "assumed-role" format. As an example if you are a real IAM user it comes in this format 'arn:aws:iam::470000000009:user/Username'. Another problem is that a user could be coming from a different account number, so it is somewhat important to have that information.

**Comment by rayj-pgi** [comment]
I didn't get any feedback on this one. Let us know if you are still interested in this feature.
