### ISSUE TITLE
Node.js deprecated, cloudFormation templates needs to be updated

### ISSUE THREAD

**Issue by Nipazz** [GorillaStack/auto-tag#50]
On the https://github.com/GorillaStack/auto-tag/blob/master/cloud_formation/s3object_template/autotag_s3object_main-template.json -file at row 71, the runtime is nodejs6.10. Using this template makes the stack roll back at CloudFormation, because Node 6 is deprecated. Simply changing this line to nodejs8.10 works, but as I'm fairly inexperienced at using GitHub, I prefer just writing about this issue instead of creating Pull Request.

The same issue seems to be here too: https://github.com/GorillaStack/auto-tag/blob/master/cloud_formation/event_multi_region_template/autotag_event_main-template.rb .

On the first file, the default folder and file are outdated (auto-tag-0.3.0.zip), but that's not a huge problem, as creating my own files is simple

**Comment by rayj-pgi** [comment]
ahh yes, I'll see if I can put in a PR for the nodejs version shortly. 

The pre-built zip files have definitely not been updated in a long time that's why the README includes instructions on how to build your own zip.

Thanks Nipazz!

**Comment by rayj-pgi** [comment]
#53 took care of this
