### ISSUE TITLE
StackSet Failure

### ISSUE THREAD

**Issue by mcburn13** [GorillaStack/auto-tag#60]
had run the prerequisite stacks for the roles in child/master accounts, ran the auto-tag stack in the master account, without issue. When running the stackset, I chose all regions, making the MainAwsRegion us-east-1 and entered all of the child account #s comma separated.  The stack instances show 100 and all but two show as outdated with the operation returning "failed".   On the two accounts (out of 13) that I ran this against that it created any resources, it appears to only have created the SNS topic/subscription and Cloudwatch rule.  The SNS topic points to a subscriber of a Lambda AutoTag function within its own account that doesn't exist.  I don't see any event in the stack where it even attempted to create this Lambda function (in child account)

**Comment by mcburn13** [comment]
Thanks folks!  I guess originally it felt like this can be used to deploy to multiple accounts which would be a great feature! Anyway, I am somewhat green in this area, so finally got it working on a few accounts, realized it requires an actual CloudTrail and not the "default 90 days of activity-cloudtrail" (after ripping out templates and rebuilding about 10x).  
My only other wishlist item is for this to continue to be developed so that it will tag any resource that allows.

**Comment by rayj-pgi** [comment]
great news! enjoy!
