### ISSUE TITLE
Adding hard-coded or other custom tags

### ISSUE THREAD

**Issue by varunchandak** [GorillaStack/auto-tag#62]
I want to add more tags such as `ManagedBy` or `Owner`.

**Comment by rayj-pgi** [comment]
Where is the value for this tag going to come from?

I've talked about how to add more global tags here: https://github.com/GorillaStack/auto-tag/issues/35#issuecomment-504107774

**Comment by rayj-pgi** [comment]
I didn't really get an answer so I'm going to close this, let me know if you can clarify what you are trying to do.

**Comment by gjacobsatl** [comment]
> I suppose we could talk about adding this in a way where you don't have to edit the code...if that is what you are looking for.

That would be awesome, or even if we only had to edit in one place. Especially if there were various variables we could use in generating the values (e.g. availability_zone for an ec2 instance).

**Comment by rayj-pgi** [comment]
I _think_ I've added this feature to master. Please check out the changes to the [README-Custom Tags](README.md#custom-tags) and the examples.

Right now if you use the [deploy-autotag.sh](deploy-autotag.sh) script you can run 'update-master' and it will deploy with this new code for you.

If you'd like to populate the AZ for an EC2 instance you would supply something like this to the `--custom-tags` parameter:

```json
{
  "AutoTag_EC2_AZ": "$event.responseElements.instancesSet.items.0.placement.availabilityZone"
}
```

**Comment by rayj-pgi** [comment]
Check this feature out in 0.5.3
