### ISSUE TITLE
CloudFormation JSON issue, subscription not added.

### ISSUE THREAD

**Issue by varunchandak** [GorillaStack/auto-tag#64]
Deployed yesterday, took me few hours to figure out why resources were not getting tagged.

**Issue**: SNS topic were having only 1 Lambda subscription:
![image](https://user-images.githubusercontent.com/18713091/67366515-4482da00-f591-11e9-8552-cee57e7d8708.png)

**How did I resolve:**
By adding the StackSet-AutoTag lambda function as subscription.
![image](https://user-images.githubusercontent.com/18713091/67366753-b1966f80-f591-11e9-80eb-0088c098fb48.png)

**Comment by varunchandak** [comment]
Checked the template. Looks like the stack name is randomly generated and the lambda function is created with the same name as stack name.

**Comment by rayj-pgi** [comment]
Ya, that is a bit of a pain. I'll try to come up with a solution...

**Comment by varunchandak** [comment]
That's easy. Rename the `FunctionName` from `{AWS:Stack}` to `AutoTag`.

**Comment by rayj-pgi** [comment]
> That's easy. Rename the `FunctionName` from `{AWS:Stack}` to `AutoTag`.

I'm looking at the `FunctionName` and it is already set to `AutoTag`, right?

https://github.com/GorillaStack/auto-tag/blob/master/cloud_formation/event_multi_region_template/autotag_event_main-template.rb#L55

**Comment by rayj-pgi** [comment]
Ok, I found where people are getting the old template. Let me fix this...

**Comment by rayj-pgi** [comment]
The GorillaStack S3 bucket template is outdated. This one has the latest.

https://github.com/GorillaStack/auto-tag/blob/master/cloud_formation/event_multi_region_template/autotag_event_main-template.json

**Comment by varunchandak** [comment]
@rayj-pgi Is this pushed to master ? I tried redeploying it in my account and the lambda function is created as `AutoTag-StackSet-XXXXX-xxxxx-xxxxx`

**Comment by rayj-pgi** [comment]
Yes. Did you look at the link I sent? https://github.com/GorillaStack/auto-tag/blob/master/cloud_formation/event_multi_region_template/autotag_event_main-template.json#L65

**Comment by rayj-pgi** [comment]
I've updated the README to point to the main stack template on github cb5889c until we can update the main stack template in the GorillaStack S3 bucket.
