### ISSUE TITLE
Lambda Triggering doesn't work with new CLI instructions

### ISSUE THREAD

**Issue by Arkessler** [GorillaStack/auto-tag#65]
Hello,

I recently followed the stack-set instruction set for standing up the main stack via aws CLI. Those instructions were modified in this commit 9 days ago (https://github.com/GorillaStack/auto-tag/commit/801c91cb11834c0f8d00cafea53d1543f3dcde38).

I haven't been able to identify the root cause, but when deployed according to these instructions (main stack as a stack set instead of a stack), I don't see any of the tagging happening. I have tried this in both a single account and across several accounts multiple times. As far as I can tell, the cloud event rule is either not triggering, or the lambda is failing to activate. 

I tried sending a CloudWatch entry for a LoadBalancer creation to the Lambda as a test event and received an error. 
The test event was
```
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "xxxxxxxxxxxxx",
        "arn": "xxxxxxxxxxxxxx",
        "accountId": "xxxxxxxxxxx",
        "accessKeyId": "xxxxxxxxxxxxx",
        "sessionContext": {
            "sessionIssuer": {
                "type": "Role",
                "principalId": "xxxxxxxxxxx",
                "arn": "arn:aws:iam::xxxxxxxx",
                "accountId": "xxxxxxxx",
                "userName": "xxxxxxxxxx"
            },
            "webIdFederationData": {},
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2019-10-23T18:49:27Z"
            }
        }
    },
    "eventTime": "2019-10-23T19:05:07Z",
    "eventSource": "elasticloadbalancing.amazonaws.com",
    "eventName": "CreateLoadBalancer",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "50.203.56.66",
    "userAgent": "console.ec2.amazonaws.com",
    "requestParameters": {
        "availabilityZones": [
            "us-east-1d"
        ],
        "loadBalancerName": "test-autotag-delete-me",
        "tags": [
            {
                "key": "Name",
                "value": "test-autotag-delete-me"
            }
        ],
        "listeners": [
            {
                "protocol": "HTTP",
                "loadBalancerPort": 80,
                "instanceProtocol": "HTTP",
                "instancePort": 80
            }
        ],
        "scheme": "internet-facing"
    },
    "responseElements": {
        "dNSName": "test-autotag-delete-me-338749204.us-east-1.elb.amazonaws.com"
    },
    "requestID": "c046f8f6-95be-457c-9434-94ddec222a57",
    "eventID": "90ba9aee-4d15-452d-843a-286a81dbb705",
    "eventType": "AwsApiCall",
    "apiVersion": "2012-06-01",
    "recipientAccountId": "xxxxxxxxxxxxxxxx"
}
```

I no longer have the error message but it was something along the lines of "Cannot set `recipientAccountId` on unidentified".

I previously deployed with the main stack as a single stack instead of a set and saw the desired behavior. I am about to retry deploying to a single account with the old instructions to see if I can get it working again.

**Comment by rayj-pgi** [comment]
Please give it a try but use this template for the main stack-set until we can get the one in the GorillaStack S3 bucket updated.

https://github.com/GorillaStack/auto-tag/blob/master/cloud_formation/event_multi_region_template/autotag_event_main-template.json

**Comment by rayj-pgi** [comment]
I've updated the README to point to the main stack template on github cb5889c until we can update the main stack template in the GorillaStack S3 bucket.
