### ISSUE TITLE
Cannot get basic functionality

### ISSUE THREAD

**Issue by ateterine** [GorillaStack/auto-tag#69]
Not sure if I'm missing or have provisioned anything incorrectly but none of the resources I create are being tagged and no invocations of Lambda occur. I have tried provisioning it via console and CLI.

My setup:
1 account
1 region

Deployed both roles,
Deployed both stacksets and stacks within

Is it possible for this to work in the same account same region? 

Any help will be appreciated. Thank you!

**Comment by rayj-pgi** [comment]
Hi, try using this main stack template instead of the one in the GorillaStack S3 bucket.

https://raw.githubusercontent.com/GorillaStack/auto-tag/master/cloud_formation/event_multi_region_template/autotag_event_main-template.json

**Comment by rayj-pgi** [comment]
You may need to take the collector stack down and bring it back up again after altering the main stack.

**Comment by ateterine** [comment]
Awesome! Thanks!

**Comment by rayj-pgi** [comment]
I've updated the README to point to the main stack template on github cb5889c
