### ISSUE TITLE
EC2 Instances not Auto-Tagged

### ISSUE THREAD

**Issue by jennales** [GorillaStack/auto-tag#7]
I successfully created the "autotag" CloudFormation stack using the instructions in the readme in this repo.  I can see the cloudtrail logs being generated in the S3 bucket that the stack creates, however, I'm not seeing any tags being added after I launch a new EC2 instance.

Perhaps I missed a step in the auto-tag setup or the instance launch process that tells the tags to auto add themselves?  Let me know if you need any additional info from me that would be helpful in figuring out what's going on.

Thanks in advance!

**Comment by aae42** [comment]
you may have to wait a number of minutes for them to pop up

On Tuesday, May 31, 2016, JennaTime <notifications@github.com> wrote:

> I successfully created the "autotag" CloudFormation stack using the
> instructions in the readme in this repo. I can see the cloudtrail logs
> being generated in the S3 bucket that the stack creates, however, I'm not
> seeing any tags being added after I launch a new EC2 instance.
>
> Perhaps I missed a step in the auto-tag setup or the instance launch
> process that tells the tags to auto add themselves? Let me know if you need
> any additional info from me that would be helpful in figuring out what's
> going on.
>
> Thanks in advance!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GorillaStack/auto-tag/issues/7>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABIFHWJFVIV-7zAKBQ9aBNHula5IYUGAks5qHDMYgaJpZM4IqgzZ>
> .
>


-- 
Sent from my phone

**Comment by jennales** [comment]
You are correct aae42.  I just went to check the instance I created this morning about an hour ago and the AutoTag_Creator tag is now there.  It's not very pretty (I'd like to simplify it to be Creator (key): userName (value), however, it is working!

**Comment by em0ney** [comment]
Awesome.  Yeah, it takes 5-7 minutes for CloudTrail to write to events to s3
