### ISSUE TITLE
Build and Package the App

### ISSUE THREAD

**Issue by ateterine** [GorillaStack/auto-tag#70]
Hi all,

Please forgive my ignorance, but was wondering how do I 'build/compile' updated code to deploy to Lambda?

Thanks!

**Comment by rayj-pgi** [comment]
Hey there, no problem. There are some scripts setup in the `package.json`, just run `npm run compile` and it will drop code in a `lib/` dir.

**Comment by rayj-pgi** [comment]
actually this is a bit more comprehensive

once:
```
npm install
```

each build:
```
npm run compile

cp -u package.json lib/
npm install --prefix lib/ --production
rm -rf lib/node_modules/aws-sdk
```

**Comment by rayj-pgi** [comment]
The new deploy script will perform these build steps for us now. Check the [/README.md]
