### ISSUE TITLE
AutoTag not tagging snapshots when AMI is created

### ISSUE THREAD

**Issue by varunchandak** [GorillaStack/auto-tag#72]
AMI is created with autotags, but not it's corresponding snapshots. Please find below screenshots of the same.

AMI:
![image](https://user-images.githubusercontent.com/18713091/68936748-3192ac80-07c1-11ea-9749-566e730ea0da.png)

Snapshot:
![image](https://user-images.githubusercontent.com/18713091/68936864-5f77f100-07c1-11ea-86ff-79f732db3d94.png)

**Comment by rayj-pgi** [comment]
Hi @varunchandak, do you have the log entry for this snpshot?

**Comment by rayj-pgi** [comment]
Well maybe there isn't a `CreateSnapshot` sent...I bet the `CreateImage` results in both an ami and snap entity...

I should be able to test this out.

**Comment by rayj-pgi** [comment]
Let's see, so the Image doesn't include the snapshot ID.

```json
{
  "eventTime": "2019-11-12T15:22:23Z",
  "eventSource": "ec2.amazonaws.com",
  "eventName": "CreateImage",
  "awsRegion": "us-east-1",
  "sourceIPAddress": "1.1.1.1",
  "userAgent": "aws-sdk-go/1.16.24 (go1.12.5; linux; amd64)",
  "requestParameters": {
    "instanceId": "i-0862b1181beda9999",
    "name": "asdf 1.1.2 2019-11-12T15-14-01Z"
  },
  "responseElements": {
    "requestId": "84da153d-3f8f-4fb2-927e-d69b07979999",
    "imageId": "ami-0d4d5d96cc8799999"
  }
}
```

**Comment by rayj-pgi** [comment]
Give it a shot 52b6226

**Comment by varunchandak** [comment]
Thanks. Will replacing `src/workers/autotag_ami_worker.js` work along with the main CF template ?

**Comment by rayj-pgi** [comment]
You'll probably just want to make a new package, those steps are here.

https://github.com/GorillaStack/auto-tag/issues/70

**Comment by varunchandak** [comment]
Working perfectly... !! Thanks for the prompt action!

**Comment by rayj-pgi** [comment]
Glad to hear that worked for you @varunchandak! Thanks for making us aware of the issue!
