### ISSUE TITLE
autotag_event_main-template.json missing CustomTags

### ISSUE THREAD

**Issue by arueth** [GorillaStack/auto-tag#75]
When trying to run the ./deploy_autotag.sh script I get the following error:
An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [CustomTags] do not exist in the template

It looks like https://raw.githubusercontent.com/GorillaStack/auto-tag/292dec9d863d1df48001dbd5503adceee3c23a7d/cloud_formation/event_multi_region_template/autotag_event_main-template.json does not include CustomTags, but master does.

**Comment by jcajkovic** [comment]
Have the same issue, is there some ETA when this is going to be fixed ? Thanks

**Comment by rayj-pgi** [comment]
Thanks for this. I've just commit a fix to master. Give it another shot.

**Comment by jcajkovic** [comment]
the fix works on master, however the custom tags are not propagated on AWS Resource itself.

when I try:

./deploy_autotag.sh --region $AWS_REGION --s3-bucket $S3_BUCKET_NAME --release-version $AUTOTAG_VERSION --custom-tags '{"CostCenter": "costcenter"}' create

I can see only the default tags.

when I try

./deploy_autotag.sh --region $AWS_REGION --s3-bucket $S3_BUCKET_NAME --release-version $AUTOTAG_VERSION --custom-tags '{"AutoTag_CostCenter": "costcenter"}'

I do not see any tags on the resource.

I am creating EC2 instances for testing.

**Comment by jcajkovic** [comment]
Do we have ETA when this is going to be in released version 0.5.3 ? I'm implementing this in GitLab pipeline and the issue is that I do not want to do this in 2 step first deploy latest version and afterwards to upgrade to master.

**Comment by rayj-pgi** [comment]
Glad to hear everything is functioning @jcajkovic. I've put the new release 0.5.3 up, let me know how that works.

**Comment by jcajkovic** [comment]
I can confirm it works on released 0.5.3 version.
