### ISSUE TITLE
Deployed stacks successfully but tagging did not happen

### ISSUE THREAD

**Issue by cherylf** [GorillaStack/auto-tag#76]
Hi,

I followed the steps to deploy autotag via CloudFormation and successfully deployed the required stacks. CloudTrail is automatically enabled for an AWS Account, so I didn't create a trail at first but I later created a trail because auto tagging didn't happen. After the trail was created, auto tagging still didn't happen when I created a bucket. The CloudFormation template specify that the Lambda function should be triggered by an SNS topic, and this is different from the architecture shown on this page https://www.gorillastack.com/news/gorillastack-presents-auto-tag/ 

So I'd like to know what I'm missing and what should trigger the Lambda function?

Thanks in advance for your help.

**Comment by rayj-pgi** [comment]
CloudTrail events are sent to SNS which are sent across the various regions back to the Lambda function. 

Did you deploy with the 'deploy.sh' script as detailed in the README? This takes care of everything for you.

**Comment by rayj-pgi** [comment]
Closing this one since there was no answer, please re-open if you have any other questions.
