### ISSUE TITLE
Invocation of autotag_autoscale_worker results in DryRun error

### ISSUE THREAD

**Issue by trevorlatson** [GorillaStack/auto-tag#84]
Any time the AutoScaling worker is invoked, I get the following errors:

`2020-10-02T13:59:42.595Z	daeb3170-2b2c-4fc9-8595-19c75f99cd46	INFO	CloudTrail Event - Error Code: Client.DryRunOperation
`

`2020-10-02T13:59:42.595Z	daeb3170-2b2c-4fc9-8595-19c75f99cd46	INFO	CloudTrail Event - Error Message: Request would have succeeded, but DryRun flag is set.
`

I have certainly not set the DryRun flag, and all of the other worker modules (EC2, IAM, etc) are working fine. How in the world is the DryRun flag being set for this resource type only? I can't find any references in the code to "DryRun" or "dry" whatsoever.

**Comment by rayjanoka** [comment]
Well it would seem that error is from the CloudTrail event before AutoTag does any real work. [here](https://github.com/GorillaStack/auto-tag/blob/master/src/aws_cloud_trail_event_listener.js#L23)
So it would appear someone in your account is executing API commands with DryRun enabled....AutoTag should probably just ignore these.
Are you sure that your AutoScaling Groups are not being tagged?
Can you show me any more of the output? You may want to turn on some of the debug options.
