### ISSUE TITLE
The blog post seems to be outdated

### ISSUE THREAD

**Issue by pubudug** [GorillaStack/auto-tag#86]
The blog post mentioned in the README seems to be outdated now? 

* when I look at https://github.com/GorillaStack/auto-tag/blob/master/STACKSET.md it seems that the Linked Account will each contain the Lambda? But the image in the blog post shows that the Lambda exists in the main account?
* There is a mention of an sns topic there as well, but this is not visible in the image

All in all I find it difficult to understand where each of the components are deployed and how they work together.
Also I suppose some manual steps are required for setting up cloud trail? And does one setup the S3 bucket for cloud trail in the main account then, as shown in the blog post?

**Comment by pubudug** [comment]
I think I was able to understand parts of it. One thing I don't understand is in https://github.com/GorillaStack/auto-tag/blob/master/STACKSET.md under "Main Stackset" it says `Deploy this stack set first in all desired accounts in a single "master" region. This stack is responsible for consuming events from each account it is deployed to, in all regions.`. But why would I deploy the main stackset which includes the Lambda into multiple accounts? Wouldn't it be enough to deploy it in a single account?

**Comment by pubudug** [comment]
Okay. Now I understand that the main stack needs to be deployed in each of the accounts, but in a chosen region, and the collector needs to be deployed in all the accounts in all regions. But that would mean that the image in the blog post is worng, which indicates that there is a single account where the lambda is running and the events from all other accounts trigger this lambda.

**Comment by pubudug** [comment]
Can someone shed some light on this? I am quite confused :)

**Comment by joelplums** [comment]
> Can someone shed some light on this? I am quite confused :)

Hi @pubudug thanks for reaching out with the comment. The linked blog post is from v1 of the architecture prior to the great contributions form @rayjanoka :clap: 

Fair to say that the blog post while previously relevant is now outdated.

I think a new architecture diagram would be helpful. Just reading through the main-template and collector-template. A cloudwatch event rule is placed on the cloudwatch event bus in each account/region (if using multi region stack set) subscribing to relevant events and publishing it to the SNS topic in the `MainAwsRegion` where the main-template is deployed.

My understanding is that this architecture is designed to operate independently within the bounds of single AWS Accounts to avoid the complexity of multi-account architectures with role assumption.

Hope this is helpful, feel free to ask any follow up questions you may have

**Comment by pubudug** [comment]
I sketched something for my own understanding. Feel free to use it if you feel like doing so.

![image](https://user-images.githubusercontent.com/516092/109613903-1cff3280-7b32-11eb-91fd-112dea01d011.png)

**Comment by rayjanoka** [comment]
The blog post is from 2015, it is not totally accurate anymore. Please use the README.
