### ISSUE TITLE
How deploy to multiple accounts or at organisation level?

### ISSUE THREAD

**Issue by cdtiwari-ebi** [GorillaStack/auto-tag#88]
I am looking forward to see how can I deploy at the master account level and it will deploy under every organisation unit account?

**Comment by rayjanoka** [comment]
we only support the deployment of a single account with multiple regions

**Comment by cdtiwari-ebi** [comment]
I understood, Is there any plans to manage at AWS organisation level as the new feature.
For time being I will deploy under each and every account, Thanks for your comment @rayjanoka

**Comment by ecout** [comment]
RTM, use Cloud Formation Stack Sets. That's not the responsibility of Gorilla Stack but of the DevOps Engineer implementing their solution. We're supposed to know how to use Cloud Formation.
