### ISSUE TITLE
How to debug why it's not tagging resources?

### ISSUE THREAD

**Issue by cdtiwari-ebi** [GorillaStack/auto-tag#89]
Hi Team,

I have tried deploying using below command;
`./deploy_autotag.sh -r eu-west-2 --s3-bucket <autotag-bucket> --profile <myprofile> -ld --s3-profile <myprofile> create`

I am using same profile for `--profile`, `--s3-profile` At the end I am getting successfully deployed message
**The AutoTag deployment is complete**

After the deployment I tried spinning few ec2 instances but not instance, network, volume nothing is tagged. I was wondering where can I see errors and logs because I am trying to use debug option `-ld` as suggested in documentation

I appreciate your efforts and help.

**Comment by rayjanoka** [comment]
The Lambda Function should have some logs

**Comment by cdtiwari-ebi** [comment]
Here are my steps;
1. `./deploy_autotag.sh -r eu-west-2 --s3-bucket <autotag-bucket> --profile <myprofile> -ld --s3-profile <myprofile> create`
2. Manually check the stack in each region and waited for `CREATE_COMPLETE`
3. Spin few EC2 instances, waiting for Tags to enable. Waited for 5-10min but no tags.
4. Go to Lambda function `AutoTag`, 'Monitor' increase the window until 1w for logs and traces. 
5. Nothing was visible.   
Question: Is there any way to check errors If there is anything?

**Comment by cdtiwari-ebi** [comment]
![Screenshot 2021-03-04 at 21 38 56](https://user-images.githubusercontent.com/44263335/110034241-1b9c5880-7d32-11eb-9d26-73295e312fa0.png)
This is what I got after a lot of try and catch. Is it useful to understand what's wrong with happening?

**Comment by rayjanoka** [comment]
ok, the problem is likely that you do not have CloudTrail enabled in your account.

https://github.com/GorillaStack/auto-tag#prerequisites

**Comment by cdtiwari-ebi** [comment]
Thanks for helping.
