### ISSUE TITLE
unable to tag resources

### ISSUE THREAD

**Issue by shashanksingh24** [GorillaStack/auto-tag#9]
Hi all,
I successfully created the template but unable to tag the resource after deploy the template through cloud formation. Is there any extra steps that has to be done after deploy cloud formation template. If any plz tell me the detail.

**Comment by MegaAmoonguss** [comment]
You have to wait for the CloudTrail logs to appear before the resources get tagged. This can take a couple of minutes, so be patient. If you see the logs appear but the resource is still not tagged, then you are encountering an actual error. You can also see if actual errors are arising via the "Monitoring" tab in Lambda.

**Comment by seren** [comment]
Yeah, I kept thinking something was wrong but eventually realized I needed to wait, sometimes more than 5 minutes. No biggie, but potentially confusing when testing it.

**Comment by em0ney** [comment]
Hey @shashanksingh24 @MegaAmoonguss @seren 

Yes, this is just an implication of the nature of CloudTrail.  Can take 5-7 minutes for the event to be written to logs.  I'll include this more clearly on the README

Thanks!
