### ISSUE TITLE
Node.js.10 EOL

### ISSUE THREAD

**Issue by ssi-hu-tamas-sipos** [GorillaStack/auto-tag#96]
Will this tool work if we update the node.js 10 to 14? Just starting to get EOL messages from Amazon.
Meanwhile we started to get deprecation warnings about the Python 2.7.
Thanks.

**Comment by ssi-hu-tamas-sipos** [comment]
Same for Python 2.7.

**Comment by jr-air** [comment]
Had the same question. Auto-Tag being updated to support NodeJS 14 would be ideal.

**Comment by chanakanissanka** [comment]
We have the same concern given AWS is retiring 10.x lamda. Any possibility of getting NodeJS12.x (14.x would be ideal)

**Comment by em0ney** [comment]
Should work fine with node14, but some problems in cloudformation support for inline functions with node14 right now (weird bug). will bump to node12 to buy some time in the meantime

**Comment by em0ney** [comment]
Handled by https://github.com/GorillaStack/auto-tag/pull/97
