### ISSUE TITLE
Source IP address tag

### ISSUE THREAD

**Issue by tomass222** [GorillaStack/auto-tag#99]
Hello all,

please is somebody here who can help me to solve issue with using custom tag for source IP? I am getting error message. I read also another threads here, but there isn't any solution. I will be very happy if somebody can help me here.

[cloudshell-user@ip-10-0-29-241 ~]$ ./deploy_autotag.sh --region eu-central-1 --s3-bucket tomas-test-gorilla --release-version latest create --custom-tags '{"AutoTag_IPtest": "$event.sourceIPAddress"}'
    _______       __         _______
   |   _   .--.--|  |_.-----|       .---.-.-----.
   |.  1   |  |  |   _|  _  |.|   | |  _  |  _  |
   |.  _   |_____|____|_____`-|.  |-|___._|___  |
   |:  |   |                  |:  |       |_____|
   |::.|:. |                  |::.|
   `--- ---'                  `---'

******
****** Create Stacks
******

The tomas-test-gorilla S3 Bucket already exists, skipping bucket create
Initializing AutoTag release version 0.5.3
Creating the Main CloudFormation Stack...
parse error: Invalid numeric literal at line 28, column 48
[cloudshell-user@ip-10-0-29-241 ~]$

**Comment by rayjanoka** [comment]
This is strange because I don't have the issue. 

As you can see I can run the same command without issue.

What version of Bash are you running?

```
➜ env bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

➜ ./deploy_autotag.sh --profile ray --region eu-central-1 --s3-bucket test-gorilla123123 --release-version latest create --custom-tags '{"AutoTag_IPtest": "$event.sourceIPAddress"}'
    _______       __         _______
   |   _   .--.--|  |_.-----|       .---.-.-----.
   |.  1   |  |  |   _|  _  |.|   | |  _  |  _  |
   |.  _   |_____|____|_____`-|.  |-|___._|___  |
   |:  |   |                  |:  |       |_____|
   |::.|:. |                  |::.|
   `--- ---'                  `---'


******
****** Create Stacks
******

The test-gorilla123123 S3 Bucket does not exist for this profile, creating bucket
Creating the test-gorilla123123 secure S3 Bucket with all public access blocked...
{
    "Location": "http://test-gorilla123123.s3.amazonaws.com/"
}
Initializing AutoTag release version 0.5.3
upload: ./autotag-0.5.3.zip to s3://test-gorilla123123/releases/autotag-0.5.3.zip
Creating the Main CloudFormation Stack...
{
    "StackId": "arn:aws:cloudformation:eu-central-1:1234567890:stack/AutoTag/b1ab03b0-84b3-11ec-8154-02cf84dfb96a"
}
Main CloudFormation Stack in eu-central-1 has been created, waiting for completion...
Main CloudFormation Stack Status: CREATE_IN_PROGRESS
```

**Comment by rayjanoka** [comment]
I found the problem. bash 4.3 or greater is required! :smile: 
this will help: 81f9cb6122be51c370f5b0bc8a87c65b52c920d8
